### ISSUE TITLE
Add LICENSE file to repo

### ISSUE THREAD

**Issue by jayvdb** [ilanschnell/bsdiff4#10]
Hi, would it be possible to add a LICENSE file to the repository?

I assume it will be [BSD-2-Clause](https://opensource.org/licenses/BSD-2-Clause) due to the heritage of bsdiff4, but a LICENSE file is how to make that unambiguous.

I am wanting to package this up as a dependency of PyUpdater.
packaging project at https://build.opensuse.org/package/show/home:jayvdb:py-new/python-bsdiff4

**Comment by ilanschnell** [comment]
Thanks!  I just added a BSD-2-Clause LICENSE file to the source, see: 02aa1dacae973d43eeefef9250217944d9cf24bf
