### ISSUE TITLE
bsdiff4 cli in verbose mode exits with exception

### ISSUE THREAD

**Issue by RafaelPAndrade** [ilanschnell/bsdiff4#12]
Installed bsdiff4 from source, for python3.

The offending line:

https://github.com/ilanschnell/bsdiff4/blob/01313edf9b5a38dacfb38fa5f1259623fceefc15/bsdiff4/cli.py#L35

I do not know much about python2 vs python3 compatibility, but using range instead of xrange seems to work for both versions.

**Comment by ilanschnell** [comment]
Thanks!  Yes, using `range` will work under both Python 2 and 3.  I just fixed it: 4a2b9ab9f86aeb2bac344170623cc5c60ac3a56e
