### ISSUE TITLE
PyArg_ParseTuple `s#` doesn't use ints for size

### ISSUE THREAD

**Issue by CFSworks** [ilanschnell/bsdiff4#13]
Commit 35a390c67bb5c07b01b3d7b271e354da7fb36952 began defining `PY_SSIZE_T_CLEAN` - the [meaning of this macro in the API](https://docs.python.org/3/c-api/arg.html) is as follows:

`For all # variants of formats (s#, y#, etc.), the type of the length argument (int or Py_ssize_t) is controlled by defining the macro PY_SSIZE_T_CLEAN before including Python.h. If the macro was defined, length is a Py_ssize_t rather than an int. This behavior will change in a future Python version to only support Py_ssize_t and drop int support. It is best to always define PY_SSIZE_T_CLEAN.`

It is sometimes the case that `Py_ssize_t` is a 64-bit type while `int` is a 32-bit type, which means that `PyArg_ParseTuple` clobbers the stack of the `patch`/`diff` functions.

Both `int origDataLength, newDataLength // ...` lines should be updated to `Py_ssize_t` instead.

**Comment by ilanschnell** [comment]
Thanks for pointing this out!  I've fixed this is d10e76af3797c6265c86bc3d3b6a0e5b2e7faf14
