### ISSUE TITLE
PyUpdater installation error with setup.py bsdiff4

### ISSUE THREAD

**Issue by elgizabbasov** [ilanschnell/bsdiff4#19]
Hello I have an issue with downloading PyUpdater and it seems to be that the problem is with the setup.py install for bsdiff4. I used pip install PyUpdater on my VSCode terminal however I keep getting this error: 
![image](https://user-images.githubusercontent.com/72108920/120391115-d1eceb00-c2eb-11eb-9ef4-e1c2f8528ada.png)
I am using python 3.9.1 version and I can not find any solutions to this problem. It seems like its having trouble with downloading bsdiff4 lib however I tried pip install bsdiff4 as well and ended up with the same output as in the screenshot. Any help would be appreciated

**Comment by Zopolis4** [comment]
That seems to be an issue with your Visual Studio tools, you can download a precompiled wheel binary [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#bsdiff4) instead.

**Comment by ilanschnell** [comment]
The latest version 1.2.2 has compiled wheels on PyPI, such that `pip install bsdiff4` will no longer require having MSVC installed.
