### ISSUE TITLE
Requires Admin to install on Windows

### ISSUE THREAD

**Issue by Zopolis4** [ilanschnell/bsdiff4#20]
Installing bsdiff4 via `pip install bsdiff4` on windows errors out, as it requires Microsoft Visual C++ 14.0 or greater, which can be installed through VS Build Tools, or any subsets of it. Installing VS Build Tools (or any superset of it) requires admin, which I do not have on my main development machine, and the script I am writing requires bsdiff4 and Python 3.10 (for match-case). While there are precompiled .whl files for versions up to 3.9 available [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#bsdiff4), they have no versions for Python 3.10. May I suggest that you supply precompiled .whl files in the releases section, so this can be installed without admin?

**Comment by ilanschnell** [comment]
The new bsdiff4 1.2.2 release has wheels available on PyPI, such that `pip install bsdiff4` does not require having MS Visual C++ anymore.
