### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by fyears** [ilanschnell/bsdiff4#4]
Please add a license file. ;-)

Is this code licensed under 2-clause BSD license?

**Comment by ilanschnell** [comment]
Yes, BSD license.

**Comment by gloomy-ghost** [comment]
actually, no.

if you look at http://cx-bsdiff.sourceforge.net/LICENSE.txt, it's _BSD Protection License_, and is only one way compatible with the official BSD licenses from UCB.

IANAL, but the options seem to be either:
a. convince cx-bsdiff to use a real BSD license.
b. bsdiff4 needs to switch to the same license.

related debian-legal thread: https://lists.debian.org/debian-legal/2003/10/msg00344.html
