### ISSUE TITLE
Push 1.1.5 to PyPI

### ISSUE THREAD

**Issue by qrsty** [ilanschnell/bsdiff4#6]
The [package on PyPI](https://pypi.python.org/pypi/bsdiff4) is currently version 1.1.4.

I am running into the bug fixed in #5, and it would be ideal to be able to pull the latest off the package index.

It would be appreciated if this could be updated.

**Comment by karamanolev** [comment]
@ilanschnell Any news re this?

**Comment by ilanschnell** [comment]
I just upload 1.1.5 to PyPI!
